# Generated by Django 5.2.3 on 2025-06-13 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_year', models.IntegerField()),
                ('age_month', models.IntegerField()),
                ('breed', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('has_kci_certificate', models.BooleanField(default=False)),
                ('kci_certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('buy', 'Buy'), ('sale', 'Sale'), ('matting', 'Matting')], default='buy', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='puppy_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
